### ISSUE TITLE
Embedded Rak4631 in the head.

### ISSUE THREAD

**Issue by tavdog** [thezenox/breezedude#1]
Great project and good instructions!  I managed to enable serial and embed a Rak4631 in the head powered by the ws80 as well.  However the rak powered down after 24 hours.  I'm wondering if you know any more details about how the batteries and super caps work together to power the ws80.  The Rak4631 is already a very low power device so I'm hoping this can be made reliable.
<img width="430" alt="Screenshot 2024-05-15 at 8 23 23 AM" src="https://github.com/thezenox/breezedude/assets/8324295/1da1f0c0-c3d3-4e54-8cbc-e1cc3c3c0bc3">
<img width="443" alt="Screenshot 2024-05-15 at 8 23 09 AM" src="https://github.com/thezenox/breezedude/assets/8324295/5e0f47a3-420c-4544-9697-1f6036987893">

thanks again for the great documentation.

**Comment by thezenox** [comment]
I havn't electrically checked in detail yet, but the solar panel charges the super caps, if the caps fall below V_bat, the batteries kick in to keep in running. Make shure the RAK is running with 3.0V or slightly below on the input

**Comment by tavdog** [comment]
My first test was a fail as the solar panel with supercaps couldn't keep the rak powered and the batteries died.
